print("hola mundo")
print("link start")
print("Misaka Mikoto")
print("Monkey D Luffy")
print("Tokisaki Kurumi")
print("Son Goku")
print("Chisato Nishikigi")
print("Zeus")
print("Nikola Tesla")
print("Mario Bros")
print("Spiderman")
print("Zelda")
print("Steve")
# Estudia las luces y sombras
nomre=input("como te llamas?: ")
print(__name__)
print("Bienvenido",__name__)
print(__name__)
nombre = "Ismael"
print("Lilith")